server:
  port: 8081


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: bestofluck284
  jpa:
    hibernate:
      ddl-auto: update
    # hibernate 7 automatically detects PostgreSQL database-platform: org.hibernate.dialect.PostgreSQLDialect is not required to be written

    eureka:
      client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
